version: "3.8"

services:
  rentx-database:
    image: postgres
    container_name: rentx-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  rentx-api:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/rentx-api
    links:
      - rentx-database
    depends_on:
      - rentx-database

volumes:
  pgdata:
    driver: local
